In [1]:
import gensim

import sys, os

import importlib

import tensorflow as tf

In [2]:
from tensorflow.python.client import device_lib

def get_available_gpus():
    local_device_protos = device_lib.list_local_devices()
    return [x.name for x in local_device_protos if x.device_type == 'GPU']

In [3]:
get_available_gpus()

['/device:GPU:0', '/device:GPU:1']

## here you are testing whether you have gpus or no

In [4]:
with tf.device('/gpu:0'):
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
    c = tf.matmul(a, b)

with tf.Session() as sess:
    print (sess.run(c))

[[22. 28.]
 [49. 64.]]


## PATHS

In [5]:
fast_drive_path = os.path.join('/home', 'pipusteky', 'sambashare')
b_drive_path = os.path.join('/media', 'b_drive', 'sambashare_b')

machine_g_path = os.path.join(b_drive_path, 'MACHINE_G_DRIVE', 'MACHINE_G_DRIVE')

wiki_corpus_path = os.path.join(fast_drive_path, 'WORK', 'wikipedia_corpus')
zipped_wiki_corpus_path = os.path.join(wiki_corpus_path, 'enwiki-latest-pages-articles.xml.bz2')

bert_model_path = os.path.join(machine_g_path, 'BERT_MODEL')

bert_modules_path = os.path.join(bert_model_path, 'MODULES')

# /media/b_drive/sambashare_b/UNTRACED_MACHINE_G_DRIVE_FILES/BERT/DATA
untraced_folder = os.path.join(b_drive_path, 'UNTRACED_MACHINE_G_DRIVE_FILES')
bert_untraced_folder = os.path.join(untraced_folder, 'BERT')
bert_untraced_wiki_folder = os.path.join(bert_untraced_folder,'DATA', 'WIKI_CORPUS')

# add path for w2v model
w2v_model_path = os.path.join(b_drive_path, 'MODELS', 'GOOGLE_W2V_PRETRAINED',\
                              'GoogleNews-vectors-negative300.bin') 

In [7]:
sys.path.append(bert_modules_path)

import wikipedia_corpus as wiki

In [8]:
os.listdir(bert_modules_path)

['encoder.py',
 '__pycache__',
 'wikipedia_corpus.py',
 'bert_utils.py',
 '._wikipedia_corpus.py']

In [9]:
import bert_utils as bert_util

In [9]:
sys.path.append(wiki_corpus_path)

In [10]:
os.listdir(wiki_corpus_path)

['enwiki-latest-pages-articles.xml.bz2']

## YOU SHOULD TAKE THE WIKIPEDIA CORPUS AND DUMP IT INTO TF.RECORDS

In [11]:
importlib.reload(wiki)
wiki_iter = wiki.wiki_corpus_iterator(os.path.join(wiki_corpus_path, 'enwiki-latest-pages-articles.xml.bz2'))

In [12]:
next(wiki_iter)

(0,
 (['anarchism',
   'is',
   'political',
   'philosophy',
   'that',
   'advocates',
   'self',
   'governed',
   'societies',
   'based',
   'on',
   'voluntary',
   'cooperative',
   'institutions',
   'rejecting',
   'unjust',
   'hierarchy.',
   'these',
   'institutions',
   'are',
   'often',
   'described',
   'as',
   'stateless',
   'societies',
   'although',
   'several',
   'authors',
   'have',
   'defined',
   'them',
   'more',
   'specifically',
   'as',
   'institutions',
   'based',
   'on',
   'non',
   'hierarchical',
   'or',
   'free',
   'associations.',
   'anarchism',
   'holds',
   'capitalism',
   'the',
   'state',
   'and',
   'representative',
   'democracy',
   'to',
   'be',
   'undesirable',
   'unnecessary',
   'and',
   'harmful.',
   'while',
   'opposition',
   'to',
   'the',
   'state',
   'is',
   'central',
   'anarchism',
   'specifically',
   'entails',
   'opposing',
   'authority',
   'or',
   'hierarchical',
   'organisation',
   'in',


Process InputQueue-80:
Traceback (most recent call last):
  File "/home/pipusteky/anaconda3/envs/py36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/pipusteky/anaconda3/envs/py36/lib/python3.6/site-packages/gensim/utils.py", line 1193, in run
    self.q.put(wrapped_chunk.pop(), block=True)
  File "/home/pipusteky/anaconda3/envs/py36/lib/python3.6/multiprocessing/queues.py", line 82, in put
    if not self._sem.acquire(block, timeout):
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pipusteky/anaconda3/envs/py36/lib/python3.6/multiprocessing/process.py", line 261, in _bootstrap
    util._exit_function()
  File "/home/pipusteky/anaconda3/envs/py36/lib/python3.6/multiprocessing/util.py", line 322, in _exit_function
    _run_finalizers()
  File "/home/pipusteky/anaconda3/envs/py36/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
    f

In [ ]:
X = next(wiki_iter)

In [13]:
sample_wiki = [next(wiki_iter) for _ in range(142)] 

In [15]:
import pickle
with open(os.path.join(bert_untraced_wiki_folder, 'wiki_sample.pickle'),'wb') as handle:
    pickle.dump(sample_wiki, handle, pickle.HIGHEST_PROTOCOL)

In [16]:
os.listdir(bert_untraced_wiki_folder)

['data.tfrecords', 'wiki_sample.pickle']

## OK LETS TEST `dump_wiki_text_as_tf_records`

In [44]:
importlib.reload(wiki)

<module 'Wikipedia_corpus' from '/media/b_drive/sambashare_b/MACHINE_G_DRIVE/MACHINE_G_DRIVE/BERT_MODEL/MODULES/Wikipedia_corpus.py'>

In [187]:
importlib.reload(wiki)


wiki.dump_wiki_text_as_tf_records(path_to_wiki_zipped_corpus =  zipped_wiki_corpus_path,\
                                  path_to_gensim_model = w2v_model_path,\
                                  path_to_save_tf_records = bert_untraced_wiki_folder)



--> Loading the pre-trained w2v model.
--> Finished loading the pre-trained w2v model in 24.314390897750854 s.
--> Starting creation of wikipedia iterator.
--> Wikipedia iterator prepared in 7609.928758382797 s.


In [67]:
os.listdir(bert_untraced_wiki_folder)

['data.tfrecords', 'wiki_sample.pickle']

## READ THE TF.RECORDS

In [54]:
import numpy as np

In [185]:
importlib.reload(bert_util)
bert_util.inspect_tf_record_files_one_by_one(bert_untraced_wiki_folder,'data.tfrecords' )

[11074     8 14541  8222  8588    22  6939    12  1026  7493     1  2782
     1    22  5519     1     1  2109     3     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0]
[ 791 1591 2436 1579  139   15   60   58   33   84   81    1   34  799
  262    3    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0]
[  170  1579   643  1310  6358   463    82   274    12 11074   969    34
 14541 14891    16  1849  2069   103 12349     3     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0]


KeyboardInterrupt: 

In [12]:
os.listdir(bert_untraced_wiki_folder)

['data.tfrecords', 'wiki_sample.pickle']

In [11]:
data_path = os.path.join(bert_untraced_wiki_folder, 'data.tfrecords')

In [137]:
def train_iterator(filenames: list,\
                   eos_token = True,\
                  max_sequence_length = 40):
    
    """
    first and foremost; 
    
    since the max_sequence_length:: DOES NOT include the `eos` and `bos` tokens
    you MUST add 2
    
    """
    
    def parse_and_pad(seq, max_sequence_length):
        sequence_features = {'tokens':tf.FixedLenSequenceFeature([], dtype=tf.int64)}
        
        _, sequence_parsed = tf.parse_single_sequence_example(serialized=seq,\
                                                             sequence_features=sequence_features)
        
        t = sequence_parsed['tokens']
        
        if eos_token:
            t = tf.pad(t, [[0,1]], constant_values=3)
        
        
        return tf.pad(t, [[0, max_sequence_length - tf.shape(t)[0]]])
    
    # -------------- CODE ------------------------
    # you must add 2; because of <eos> and <bos> tokens
    max_sequence_length += 2
    
    dataset = tf.data.TFRecordDataset(filenames)
    
    dataset = dataset.map(lambda t, sent_length = max_sequence_length: parse_and_pad(t, sent_length))
    
    return dataset.prefetch(1).make_one_shot_iterator()

In [145]:
c = tf.constant([[1.0, 2.0], [3.0, 4.0]])

In [149]:
type(iter(range(12)))

range_iterator

In [117]:
session = tf.InteractiveSession()

/home/pipusteky/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/client/session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [138]:
itern = train_iterator(data_path)

[tf.shape(itern.get_next())[0].eval() for _ in range(12)]


[42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42]

In [154]:
session.close()

In [161]:
itern = train_iterator(data_path)

[(ind, tenx.eval()) for (ind, tenx) in enumerate(itern)]



TypeError: 'Iterator' object is not iterable

In [175]:
def intherm(INX:'Iterator'):
    
    while True:
        try:
            yield INX.get_next()
            
        except tf.errors.OutOfRangeError:
            break
        
        except:
            raise

In [176]:
for ind, tfx in enumerate(intherm(itern)):
    print(ind)
    print(tfx.eval())

/home/pipusteky/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:407: UserWarning: An unusually high number of `Iterator.get_next()` calls was detected. This often indicates that `Iterator.get_next()` is being called inside a training loop, which will cause gradual slowdown and eventual resource exhaustion. If this is the case, restructure your code to call `next_element = iterator.get_next()` once outside the loop, and use `next_element` as the input to some computation that is invoked inside the loop.
  warnings.warn(GET_NEXT_CALL_WARNING_MESSAGE)


0
[  274    12   148  8726 11074  4085    21    43  3864     1  5758     1
   676     1   794     1  6022   869    15   945  4306     7   274    12
 11074  4530     1    20  1440     3     0     0     0     0     0     0
     0     0     0     0     0     0]
1
[  325     1  4151 18585   643  8426     1    20   812     6   137    12
 11074     3     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0]
2


KeyboardInterrupt: 

In [174]:
for ind in range(10):
    if ind>=_upper_bound:
        break
        
    try:
        next_one = itern.get_next()
        print(next_one.eval())
        _counter+=1
        
    except tf.errors.OutOfRangeError:
        break
    
    

/home/pipusteky/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:407: UserWarning: An unusually high number of `Iterator.get_next()` calls was detected. This often indicates that `Iterator.get_next()` is being called inside a training loop, which will cause gradual slowdown and eventual resource exhaustion. If this is the case, restructure your code to call `next_element = iterator.get_next()` once outside the loop, and use `next_element` as the input to some computation that is invoked inside the loop.
  warnings.warn(GET_NEXT_CALL_WARNING_MESSAGE)


[ 1250  4399     1 11074  3629     5    15   584  1385     1  1408    17
     1  4896  1688   298  3270   322 14558     1  2674    21   945 15902
     3     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0]
[ 1026   361  1026  8610 13634 11074     1    15   738 11074  6554 12686
     1   162 12997    21    70 14541 12686     3     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0]
[   72    12 11074    25  1026     1     1   643  1387    15     1    50
   492     7   135    72   146     6  2817     3     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0]
[ 1233     1 10082     1  1327    71  7048     1  1140    15  1026  2782
     1     1    33    72    12  1849     1   361    18  1269    71  1802
    91    31     1     9     1  3485  1026   361  2544  4008   286     5
  5454    

In [170]:
_counter = 0
_upper_bound = 12
while True:
    if _counter>=_upper_bound:
        break
        
    try:
        next_one = itern.get_next()
        print(next_one.eval())
        _counter+=1
        
    except tf.errors.OutOfRangeError:
        break
        

/home/pipusteky/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py:407: UserWarning: An unusually high number of `Iterator.get_next()` calls was detected. This often indicates that `Iterator.get_next()` is being called inside a training loop, which will cause gradual slowdown and eventual resource exhaustion. If this is the case, restructure your code to call `next_element = iterator.get_next()` once outside the loop, and use `next_element` as the input to some computation that is invoked inside the loop.
  warnings.warn(GET_NEXT_CALL_WARNING_MESSAGE)


[1025   76    8   90  519 7999   76   25   46  887    1  274   35 2981
    3    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0]
[   17   135   274    12 11074   592  8983    59  2774     1   463    82
    23  1123     3     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0]
[   31     1  2038    28  1341    12    82  1669  1244  7999     1   492
  8827 11074   134    20  2257    18  1571     1    17  2111    18  8222
     3     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0]
[ 6116 11074     8  1300     1  2224     3     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0]
[ 468   85   72

KeyboardInterrupt: 

In [116]:
with tf.Session() as sess:
    
    kkt = train_iterator(data_path)
    
    for _ in range(12):
        print(kkt.get_next().eval())
        

Instructions for updating:
Use tf.print instead of tf.Print. Note that tf.print returns a no-output operator that directly prints the output. Outside of defuns or eager mode, this operator will not be executed unless it is directly specified in session.run or used as a control dependency for other operators. This is only a concern in graph mode. Below is an example of how to ensure tf.print executes in graph mode:
```python
    sess = tf.Session()
    with sess.as_default():
        tensor = tf.range(10)
        print_op = tf.print(tensor)
        with tf.control_dependencies([print_op]):
          out = tf.add(tensor, tensor)
        sess.run(out)
    ```
Additionally, to use tf.print in python 2.7, users must make sure to import
the following:

  `from __future__ import print_function`



TypeError: Print() missing 1 required positional argument: 'data'

In [79]:
gensim_model.index2entity[8]

'with'

In [101]:
itern

[array([11074,     8, 14541,  8222,  8588,    22,  6939,    12,  1026,
         7493,     1,  2782,     1,    22,  5519,     1,     1,  2109,
            3,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0]),
 array([ 791, 1591, 2436, 1579,  139,   15,   60,   58,   33,   84,   81,
           1,   34,  799,  262,    3,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0]),
 array([  170,  1579,   643,  1310,  6358,   463,    82,   274,    12,
        11074,   969,    34, 14541, 14891,    16,  1849,  2069,   103,
        12349,     3,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0])]

In [88]:
dataset = tf.data.TFRecordDataset(data_path)

In [89]:
x = dataset.prefetch(1)

In [92]:
print(next(x.make_one_shot_iterator()))

TypeError: 'PrefetchDataset' object is not an iterator

## NEW HUGE WIKIPEDIA FILE TESTING

In [ ]:
#tf_record_batch_iterator

In [11]:
importlib.reload(bert_util)

<module 'bert_utils' from '/media/b_drive/sambashare_b/MACHINE_G_DRIVE/MACHINE_G_DRIVE/BERT_MODEL/MODULES/bert_utils.py'>

In [12]:
os.listdir(wiki_corpus_path)

['enwiki-latest-pages-articles.xml.bz2']

In [39]:
importlib.reload(bert_util)



<module 'bert_utils' from '/media/b_drive/sambashare_b/MACHINE_G_DRIVE/MACHINE_G_DRIVE/BERT_MODEL/MODULES/bert_utils.py'>

In [66]:
importlib.reload(bert_util)

with tf.Session() as sess:
    tens_iter = bert_util.tf_record_batch_iterator(os.path.join(bert_untraced_wiki_folder,\
                                                                'data.tfrecords'),batch_size = 142, time_major = False)
    
    true_tens = sess.run(tens_iter.get_next())
    


In [67]:
true_tens

array([[    1,     8,   454, ...,     0,     0,     0],
       [  170,  2191,    23, ...,     0,     0,     0],
       [    1,  2241, 14253, ...,     0,     0,     0],
       ...,
       [   34, 19082,   270, ...,     0,     0,     0],
       [    1,   760,  1820, ...,     0,     0,     0],
       [    1,     1,  3409, ...,     0,     0,     0]])

In [ ]:
tf.reshape()

In [21]:
importlib.reload(bert_util)
bert_util.inspect_batch_of_tf_record_files(bert_untraced_wiki_folder, 'data.tfrecords')

[[    1     8   454 ...     0     0     0]
 [  170  2191    23 ...     0     0     0]
 [    1  2241 14253 ...     0     0     0]
 ...
 [  295     1     1 ...    31     3     0]
 [    1     8  2269 ...     0     0     0]
 [   26  2722     5 ...     0     0     0]]


In [16]:
os.listdir(bert_untraced_wiki_folder)

['data.tfrecords', 'wiki_sample.pickle']

In [68]:
type(iter(range(12)))

range_iterator